const String titleApp = 'Mi horóscopo diario';
const String lblTab1 = 'Sounds';
const String lblTab2 = 'Voice';
const String lblTab3 = 'Timer';
const String lblTab4 = 'Modes';
const String lblTab5 = 'Empezar';
const String lblSettings = 'Ajustes';
const String lblExit = 'Salir';
const String lblTitleTermsConditions = 'Términos y condiciones';
const String lblNew = 'Nuevo';
const String lnlRecommended = 'Recomendada';
const String lblTitle = 'Titulo';
const String lblNext = 'Siguiente';
const String lblTryAgain = 'Intentar otra vez';
const String lblMinutes = 'Minutos';
const String lblApply = 'Aplicar';
const String lblCancel = 'Cancelar';
const String lblStop = 'Detener';
const String lblUpdateApp = 'Actualización disponible';
const String lblUpdate = 'Actualizar';
const String lblTitleUpdateApp = 'Bienvenido a';
const String lblContentUpdateApp = 'te recomienda actualizar la app a la versión más reciente.';
const String lblLaunchErrorTitle = 'Update failed';
const String lblWithoutInternetTitle = 'oops! sin internet';
const String lblWithoutInternetSubtitle = 'Se requiere una conexión activa para continuar. \nPor favor, verifica tu conexión e inténtalo de nuevo.';
const String lblSkip = 'Saltar';
const String lblDone = 'Hecho';
const String lblProfile = 'Perfil';
const String lblNotData = 'Sin informacio';
const String lblElement = 'Tu elemento';
const String lblElements = 'Tus elementos';
const String lblTips = 'Tus tips';
const String lblSings = 'Tus signos';
const String lblHoroscope = 'Tu Horoscopo';
const String lblMore = 'Quiero saber mas';
const String lblNews = 'Novedades';
const String lblSingSet = 'tu signo preferido es ';


///FAILURE
const String lblNotPlay = 'Not play error';
const String lblUnknownTitle = 'Unknown Error';
const String lblUnknownDescription = 'Retry Later: Unraveling the Mystery';
const String lblParseErrorTitle = 'Data Retrieval Error';
const String lblParseErrorDescription = 'Retry Later: Pending Data Recovery';
const String lblNotFoundElementsTitle = 'No Results Found';
const String lblNotFoundElementsDescription = 'Retry Later: Exploring Alternate Paths';
const String lblUnauthorizedTitle = 'Unauthorized Access';
const String lblUnauthorizedDescription = 'Retry Later: Guarding the Gates';
const String lblNetworkTitle = 'Network Error';
const String lblNetworkDescription = 'Retry Later: Restoring Connectivity';
const String lblNotSoundFoundTitle = 'No Sound Found';
const String lblNotSoundFoundDescription = 'Retry Later: Seeking Audio Harmony';
const String lblNotSoundsFoundTitle = 'No Sounds Found';
const String lblNotSoundsFoundDescription = 'Retry Later: Seeking Audio Harmony';
const String lblNotVoiceFoundTitle = 'No Voice Detected';
const String lblNotVoiceFoundDescription = 'Retry Later: Seeking Vocal Clarity';
const String lblNotVoicesFoundTitle = 'No Voices Detected';
const String lblNotVoicesFoundDescription = 'Retry Later: Seeking Vocal Clarity';
const String lblNotSuggestionFoundTitle = 'No Suggestion Detected';
const String lblNotSuggestionFoundDescription = 'Retry Later: No suggestion';
const String lblNotSuggestionsFoundTitle = 'No Suggestions Detected';
const String lblNotSuggestionsFoundDescription = 'Retry Later: No suggestions';
const String lblNotModeFoundTitle = 'No Mode Detected';
const String lblNotModeFoundDescription = 'Retry Later: No Mode';
const String lblNotModesFoundTitle = 'No Modes Detected';
const String lblNotModesFoundDescription = 'Retry Later: No Modes';
const String lblCancelDownloadTitle = 'Cancel Download';
const String lblCancelDownloadDescription = 'Cancel Download';
const String lblBrightnessErrorTitle = 'Brightness Error';
const String lblBrightnessErrorDescription = 'Brightness Error';
const String lblAppConfigErrorTitle = 'Config Error';
const String lblAppConfigErrorDescription = 'Config Error';
const String lblAppConfigsErrorTitle = 'Configs Error';
const String lblAppConfigsErrorDescription = 'Configs Error';
const String lblUrlParseErrorTitle = 'Url parse error';
const String lblUrlParseErrorDescription = 'Url parse error description';
const String lblUrlLaunchErrorTitle = 'Url launch error';
const String lblUrlLaunchErrorDescription = 'Url launch error description';
const String lblNotSingFoundTitle = 'Not Sing Found';
const String lblNotSingFoundDescription = 'Not Sing Found';
const String lblNotSingsFoundTitle = 'Not Sings Found';
const String lblNotSingsFoundDescription = 'Not Sings Found';

///FIREBASE
const String lblRemoteConfigAppConfig = 'app_config';
const String lblRemoteConfigSings = 'sings_info';
const String lblRemoteConfigElements = 'elements_info';

///INSTRUCTIONS
const String lblInstructionModes = 'Choose the mode that best suits you and immerse yourself in an oasis of absolute tranquility';
const String lblInstructionTimer = 'Choose from a list of predefined timers or create a custom one based on your desired duration.';
const String lblInstructionVoices = 'Choose different meditations or remove the voice so you can enjoy the background sounds.';
const String lblInstructionSings = 'Descubre lo que las estrellas tienen preparado para ti. ¡Elige tu signo y encuentra tu camino estelar!';

///ADS
const String adUnitIdAndroid = 'ca-app-pub-2858479143442816~3536860373';
const String adUnitIdIos = '';
const String adUnitIdTest = 'ca-app-pub-3940256099942544/6300978111';